In [55]:
!pip install pandas
!pip install seaborn
!pip install matplotlib
!pip install mpld3
import pandas as pd
from pandas import read_csv
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy as np
import json
import os

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.20.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

[notice] A new release of pip is available: 23.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\user\anaconda3\lib\site-packages (0.11.2)
Requirement already satisfied: numpy>=1.15 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.20.3)
Requirement already satisfied: scipy>=1.0 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.7.1)
Requirement already satisfied: pandas>=0.23 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (1.3.4)
Requirement already satisfied: matplotlib>=2.2 in c:\users\user\anaconda3\lib\site-packages (from seaborn) (3.4.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.3.1)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.23->seaborn) (2021.3)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.16.0)

[notice] A new release of pip is available: 23.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\user\anaconda3\lib\site-packages (3.4.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: numpy>=1.16 in c:\users\user\anaconda3\lib\site-packages (from matplotlib) (1.20.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib) (1.16.0)

[notice] A new release of pip is available: 23.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: mpld3 in c:\users\user\anaconda3\lib\site-packages (0.5.9)
Requirement already satisfied: jinja2 in c:\users\user\anaconda3\lib\site-packages (from mpld3) (2.11.3)
Requirement already satisfied: matplotlib in c:\users\user\anaconda3\lib\site-packages (from mpld3) (3.4.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\user\anaconda3\lib\site-packages (from jinja2->mpld3) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->mpld3) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->mpld3) (1.3.1)
Requirement already satisfied: numpy>=1.16 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->mpld3) (1.20.3)
Requirement already satisfied: pillow>=6.2.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->mpld3) (8.4.0)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->mpld3) (3.0.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib->mpld3) (2.8.2)
Requirement already satisfied: six in c:\users\user\anaconda3\lib\site-packages (from cycler>=0.10->matplotlib->mpld3) (1.16.0)

[notice] A new release of pip is available: 23.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [56]:
#first, a list with the more relevant names of the columns is createad
infocol = ["Territory", "Data type", "Gender", "Highest level of education attained", "Citizenship", "TIME", "Value"]
#then, the csv files are read and we use the list created before to only have information about those
df1 = (pd.read_csv("../_datasets/ISTAT_Unemployment_rate_region_2018_2022_.csv", sep=","))[infocol]
df2 = (pd.read_csv("../_datasets/ISTAT_Activity_Rate_Region_2018-2022.csv", sep=","))[infocol]

In [57]:
#here a function is defined in order to delete rows that might not interest us
def delete_row(dataframe, column_name, value_to_delete):
    filtered_dataframe = dataframe[dataframe[column_name] != value_to_delete]

    return filtered_dataframe

In [58]:
#sometimes the year value might include information about quarters, so this is another function to take only the values with 4 digits
def y_val(dataframe):
    
    dataframe['TIME'] = dataframe['TIME'].astype('str')
    mask = (dataframe['TIME'].str.len() == 4)
    dataframe= dataframe.loc[mask]
    
    return dataframe

In [59]:
#applying the year function for the first dataframe
df1 = y_val(df1)

In [60]:
df1

,Territory,Data type,Gender,Highest level of education attained,Citizenship,TIME,Value
0,Italy,unemployment rate,males,upper and post secondary,italian,2018,8.646761
5,Italy,unemployment rate,males,upper and post secondary,italian,2019,7.928640
10,Italy,unemployment rate,males,upper and post secondary,italian,2020,7.425268
15,Italy,unemployment rate,males,upper and post secondary,italian,2021,7.469522
16,Italy,unemployment rate,males,upper and post secondary,italian,2022,6.137924
...,...,...,...,...,...,...,...
11672,Nord-est,unemployment rate,males,total,foreign,2018,9.628649
11677,Nord-est,unemployment rate,males,total,foreign,2019,9.437797
11682,Nord-est,unemployment rate,males,total,foreign,2020,8.935428
11687,Nord-est,unemployment rate,males,total,foreign,2021,6.870910
11688,Nord-est,unemployment rate,males,total,foreign,2022,6.092754

In [61]:
#applying the year function for the second dataframe
df2 = y_val(df2)

In [62]:
df2

,Territory,Data type,Gender,Highest level of education attained,Citizenship,TIME,Value
0,Nord,activity rate,males,upper and post secondary,italian,2018,84.489730
1,Nord,activity rate,males,upper and post secondary,italian,2019,84.137185
2,Nord,activity rate,males,upper and post secondary,italian,2020,82.260744
3,Nord,activity rate,males,upper and post secondary,italian,2021,82.684206
4,Nord,activity rate,males,upper and post secondary,italian,2022,83.823293
...,...,...,...,...,...,...,...
9875,Mezzogiorno,activity rate,total,upper and post secondary,total,2018,62.224117
9880,Mezzogiorno,activity rate,total,upper and post secondary,total,2019,62.466245
9885,Mezzogiorno,activity rate,total,upper and post secondary,total,2020,59.330492
9890,Mezzogiorno,activity rate,total,upper and post secondary,total,2021,61.167564
9891,Mezzogiorno,activity rate,total,upper and post secondary,total,2022,62.133111

In [63]:
#applying the deletion function to take out rows we're not interested
df2 = delete_row(df2, "Gender", "females")
df2 = delete_row(df2, "Gender", "males")
df2 = delete_row(df2, "Citizenship", "total")
df1 = delete_row(df1, "Gender", "females")
df1 = delete_row(df1, "Gender", "males")
df1 = delete_row(df1, "Citizenship", "total")

In [64]:
#Here we're excluding Italy because we want information only about the regions
df2 = delete_row(df2, "Territory", "Italy")
df1 = delete_row(df1, "Territory", "Italy")

In [65]:
df1

,Territory,Data type,Gender,Highest level of education attained,Citizenship,TIME,Value
275,Nord,unemployment rate,total,upper and post secondary,italian,2018,5.607093
280,Nord,unemployment rate,total,upper and post secondary,italian,2019,4.948992
285,Nord,unemployment rate,total,upper and post secondary,italian,2020,5.178384
290,Nord,unemployment rate,total,upper and post secondary,italian,2021,5.036280
291,Nord,unemployment rate,total,upper and post secondary,italian,2022,4.316984
...,...,...,...,...,...,...,...
11497,Centro (I),unemployment rate,total,"no educational degree, primary and lower secon...",italian,2018,11.549672
11502,Centro (I),unemployment rate,total,"no educational degree, primary and lower secon...",italian,2019,9.998387
11507,Centro (I),unemployment rate,total,"no educational degree, primary and lower secon...",italian,2020,10.639449
11512,Centro (I),unemployment rate,total,"no educational degree, primary and lower secon...",italian,2021,11.358337
11513,Centro (I),unemployment rate,total,"no educational degree, primary and lower secon...",italian,2022,8.639894

In [66]:
#creating a pivot table to have the information of the educational leval in other columns and not rows
unemployment_df = df1.pivot_table(index=['Territory', 'Citizenship', 'TIME'], columns='Highest level of education attained', values='Value', aggfunc='mean').reset_index()

In [67]:
#renaming the new columns with the unemployment info for each educational level
unemployment_df.columns.name = None  # Remove the column name
unemployment_df = unemployment_df.rename(columns={'no educational degree, primary and lower secondary school certificate': 'UNEMP_ED_1', 'upper and post secondary': 'UNEMP_ED_2', 'tertiary (university, doctoral and specialization courses)':'UNEMP_ED_3', 'TIME':'Year'})

In [68]:
unemployment_df

,Territory,Citizenship,Year,UNEMP_ED_1,UNEMP_ED_3,total,UNEMP_ED_2
0,Centro (I),foreign,2018,15.155627,10.804081,14.453227,14.836710
1,Centro (I),foreign,2019,13.568437,11.434287,14.846058,17.514611
2,Centro (I),foreign,2020,13.153746,8.624535,12.778525,13.542032
3,Centro (I),foreign,2021,13.241853,18.102600,15.194500,16.586291
4,Centro (I),foreign,2022,12.723967,12.505329,12.980380,13.377200
5,Centro (I),italian,2018,11.356605,4.986898,8.676383,9.377720
6,Centro (I),italian,2019,9.827092,5.102061,7.718597,8.193194
7,Centro (I),italian,2020,10.372889,5.024784,7.629936,7.821124
8,Centro (I),italian,2021,11.100709,4.150024,7.694963,8.114135
9,Centro (I),italian,2022,8.462975,3.369947,6.059123,6.500167
10,Mezzogiorno,foreign,2018,15.570274,17.189990,16.046920,16.964263
11,Mezzogiorno,foreign,2019,16.924579,16.836758,17.526526,19.247073
12,Mezzogiorno,foreign,2020,19.020709,17.950487,18.871393,18.689590
13,Mezzogiorno,foreign,2021,20.928654,19.874336,20.808093,20.727722
14,Mezzogiorno,foreign,2022,19.000206,17.563798,18.971048,19.229423
15,Mezzogiorno,italian,2018,24.215728,11.038761,18.566454,17.254204
16,Mezzogiorno,italian,2019,23.170330,10.296681,17.661179,16.685488
17,Mezzogiorno,italian,2020,21.780618,9.218436,16.074188,14.901700
18,Mezzogiorno,italian,2021,21.733578,8.411085,16.175574,15.629899
19,Mezzogiorno,italian,2022,19.364638,6.812687,14.076778,13.592164
20,Nord,foreign,2018,14.491531,9.137413,13.131091,12.781869
21,Nord,foreign,2019,13.519575,10.391808,12.223271,11.192228
22,Nord,foreign,2020,12.179855,10.897149,12.009307,12.133324
23,Nord,foreign,2021,12.367512,11.026852,12.264354,12.495783
24,Nord,foreign,2022,10.421102,8.387245,9.768999,9.457004
25,Nord,italian,2018,7.663050,3.335926,5.599697,5.546833
26,Nord,italian,2019,7.548570,3.097107,5.170383,4.881866
27,Nord,italian,2020,6.954854,3.224007,5.135753,5.120106
28,Nord,italian,2021,7.227654,2.975011,5.087200,4.995005
29,Nord,italian,2022,6.388568,2.391241,4.355185,4.254452
30,Nord-est,foreign,2018,15.381984,9.819867,13.479952,12.619294
31,Nord-est,foreign,2019,14.406747,10.068177,12.455572,11.210479
32,Nord-est,foreign,2020,12.020518,11.987181,11.897270,11.754628
33,Nord-est,foreign,2021,11.021124,9.334388,10.495161,10.315790
34,Nord-est,foreign,2022,10.030182,6.208408,8.828886,8.471354
35,Nord-est,italian,2018,6.678413,3.139968,4.941271,4.849491
36,Nord-est,italian,2019,6.202183,3.248361,4.454879,4.127024
37,Nord-est,italian,2020,6.316249,3.260684,4.876395,4.927196
38,Nord-est,italian,2021,6.397210,2.777307,4.529554,4.436290
39,Nord-est,italian,2022,5.598281,2.209158,3.837501,3.730644
40,Nord-ovest,foreign,2018,13.942550,8.657254,12.883018,12.920238
41,Nord-ovest,foreign,2019,12.974600,10.642936,12.051909,11.175751
42,Nord-ovest,foreign,2020,12.277353,9.928720,12.096275,12.508222
43,Nord-ovest,foreign,2021,13.224713,12.471011,13.596371,14.408137
44,Nord-ovest,foreign,2022,10.672936,10.163093,10.498555,10.377461
45,Nord-ovest,italian,2018,8.359876,3.474170,6.087053,6.088359
46,Nord-ovest,italian,2019,8.479393,2.987756,5.700288,5.468788
47,Nord-ovest,italian,2020,7.408154,3.197198,5.328483,5.268204
48,Nord-ovest,italian,2021,7.805801,3.120391,5.497647,5.419123
49,Nord-ovest,italian,2022,6.945924,2.522901,4.736643,4.653365

In [ ]:
unemployment_df.to_csv(r'C:\Users\User\Documents\GitHub\openaccesstoimmigrants\_datasets\Clean\D4\D4.csv', sep=',', index=False, encoding='utf-8'.to_json(r'C:\Users\User\Documents\GitHub\openaccesstoimmigrants\_datasets\Clean\D4\D4.json')

In [69]:
#f_unemp = unemployment_df.loc[unemployment_df['Citizenship'] == 'foreign']
#f_unemp

In [70]:
#result = df1.loc[df1['Citizenship'] == 'foreign']
#result

In [71]:
#creating a pivot table to have the information of the educational leval in other columns and not rows
activity_df = df2.pivot_table(index=['Territory', 'Citizenship', 'TIME'], columns='Highest level of education attained', values='Value', aggfunc='mean').reset_index()

In [72]:
#renaming the new columns with the unemployment info for each educational level
activity_df.columns.name = None  # Remove the column name
activity_df = activity_df.rename(columns={'no educational degree, primary and lower secondary school certificate': 'ACT_ED_1', 'upper and post secondary': 'ACT_ED_2', 'tertiary (university, doctoral and specialization courses)':'ACT_ED_3', 'TIME':'Year'})

In [73]:
activity_df

      Territory Citizenship  Year   ACT_ED_1   ACT_ED_3      total   ACT_ED_2
0    Centro (I)     foreign  2018  70.985618  77.124190  73.572533  75.708602
1    Centro (I)     foreign  2019  70.615605  75.937080  73.539525  76.776958
2    Centro (I)     foreign  2020  66.399470  68.671068  68.004095  70.110227
3    Centro (I)     foreign  2021  66.442788  71.376057  69.614376  73.098578
4    Centro (I)     foreign  2022  68.150298  74.444015  70.789589  72.925446
5    Centro (I)     italian  2018  52.889158  83.546888  67.794273  71.418533
6    Centro (I)     italian  2019  52.150330  83.869037  67.642946  71.001206
7    Centro (I)     italian  2020  49.991570  82.418189  66.140077  69.852723
8    Centro (I)     italian  2021  50.522212  83.899395  66.848048  70.399843
9    Centro (I)     italian  2022  51.609045  83.923159  67.995490  71.828835
10  Mezzogiorno     foreign  2018  66.097724  71.544665  66.715357  67.187872
11  Mezzogiorno     foreign  2019  66.055395  65.841146  65.247186  63.178155
12  Mezzogiorno     foreign  2020  61.716367  55.005406  59.997375  57.003637
13  Mezzogiorno     foreign  2021  63.320470  58.843586  61.888849  59.350414
14  Mezzogiorno     foreign  2022  63.442347  60.235821  62.571852  61.264202
15  Mezzogiorno     italian  2018  41.577883  74.639067  53.233826  59.857702
16  Mezzogiorno     italian  2019  40.642789  75.097647  53.163171  60.145473
17  Mezzogiorno     italian  2020  38.809179  74.371937  51.099076  57.092398
18  Mezzogiorno     italian  2021  39.703686  75.412764  52.383436  58.786052
19  Mezzogiorno     italian  2022  40.331041  75.942163  53.174318  59.487311
20         Nord     foreign  2018  68.289759  76.686424  72.931198  78.395477
21         Nord     foreign  2019  68.257518  76.713407  72.899590  78.430684
22         Nord     foreign  2020  62.080906  71.332343  67.639693  74.937094
23         Nord     foreign  2021  64.769660  74.721646  70.159186  76.261093
24         Nord     foreign  2022  65.698128  76.511609  71.207475  76.864817
25         Nord     italian  2018  55.320980  86.141796  70.329751  75.863703
26         Nord     italian  2019  55.708748  85.910280  70.676994  76.024817
27         Nord     italian  2020  53.970334  84.271635  68.906944  73.921695
28         Nord     italian  2021  54.163318  85.553606  69.213628  74.061972
29         Nord     italian  2022  54.849589  86.307408  70.253738  75.355582
30     Nord-est     foreign  2018  67.473834  76.487557  73.376928  79.708734
31     Nord-est     foreign  2019  67.704574  76.943319  73.719380  79.938751
32     Nord-est     foreign  2020  62.688161  75.437066  70.304117  77.875076
33     Nord-est     foreign  2021  63.913195  77.036717  71.090152  77.882568
34     Nord-est     foreign  2022  65.197743  78.276261  71.938108  77.516503
35     Nord-est     italian  2018  55.556846  85.724218  70.800658  76.656790
36     Nord-est     italian  2019  55.295821  85.436213  71.252621  77.447567
37     Nord-est     italian  2020  54.445613  83.740433  69.573899  74.922599
38     Nord-est     italian  2021  54.174218  85.298496  69.505691  74.410024
39     Nord-est     italian  2022  55.003484  86.232490  70.747591  76.074892
40   Nord-ovest     foreign  2018  68.802661  76.827490  72.617672  77.313317
41   Nord-ovest     foreign  2019  68.601709  76.536952  72.306542  77.109207
42   Nord-ovest     foreign  2020  61.716206  68.043631  65.711014  72.239657
43   Nord-ovest     foreign  2021  65.327416  72.853186  69.474620  74.893586
44   Nord-ovest     foreign  2022  66.026004  75.131896  70.651191  76.266436
45   Nord-ovest     italian  2018  55.156700  86.439320  69.985466  75.260497
46   Nord-ovest     italian  2019  55.998608  86.256693  70.256830  74.955011
47   Nord-ovest     italian  2020  53.640038  84.664571  68.419710  73.171798
48   Nord-ovest     italian  2021  54.156985  85.742349  69.000339  73.800469
49   Nord-ovest     italian  2022  54.741921  86.361940  69.894383  74.817090

In [74]:
#after making sure there's mostly numerical numbers in both dataframes we make the merge
DF5 = pd.merge(unemployment_df, activity_df, on=['Territory', 'Citizenship', 'Year'], how='outer')

Merge Unemployment rate x Activity rage (by educational level)

In [75]:
DF5

,Territory,Citizenship,Year,UNEMP_ED_1,UNEMP_ED_3,total_x,UNEMP_ED_2,ACT_ED_1,ACT_ED_3,total_y,ACT_ED_2
0,Centro (I),foreign,2018,15.155627,10.804081,14.453227,14.836710,70.985618,77.124190,73.572533,75.708602
1,Centro (I),foreign,2019,13.568437,11.434287,14.846058,17.514611,70.615605,75.937080,73.539525,76.776958
2,Centro (I),foreign,2020,13.153746,8.624535,12.778525,13.542032,66.399470,68.671068,68.004095,70.110227
3,Centro (I),foreign,2021,13.241853,18.102600,15.194500,16.586291,66.442788,71.376057,69.614376,73.098578
4,Centro (I),foreign,2022,12.723967,12.505329,12.980380,13.377200,68.150298,74.444015,70.789589,72.925446
5,Centro (I),italian,2018,11.356605,4.986898,8.676383,9.377720,52.889158,83.546888,67.794273,71.418533
6,Centro (I),italian,2019,9.827092,5.102061,7.718597,8.193194,52.150330,83.869037,67.642946,71.001206
7,Centro (I),italian,2020,10.372889,5.024784,7.629936,7.821124,49.991570,82.418189,66.140077,69.852723
8,Centro (I),italian,2021,11.100709,4.150024,7.694963,8.114135,50.522212,83.899395,66.848048,70.399843
9,Centro (I),italian,2022,8.462975,3.369947,6.059123,6.500167,51.609045,83.923159,67.995490,71.828835
10,Mezzogiorno,foreign,2018,15.570274,17.189990,16.046920,16.964263,66.097724,71.544665,66.715357,67.187872
11,Mezzogiorno,foreign,2019,16.924579,16.836758,17.526526,19.247073,66.055395,65.841146,65.247186,63.178155
12,Mezzogiorno,foreign,2020,19.020709,17.950487,18.871393,18.689590,61.716367,55.005406,59.997375,57.003637
13,Mezzogiorno,foreign,2021,20.928654,19.874336,20.808093,20.727722,63.320470,58.843586,61.888849,59.350414
14,Mezzogiorno,foreign,2022,19.000206,17.563798,18.971048,19.229423,63.442347,60.235821,62.571852,61.264202
15,Mezzogiorno,italian,2018,24.215728,11.038761,18.566454,17.254204,41.577883,74.639067,53.233826,59.857702
16,Mezzogiorno,italian,2019,23.170330,10.296681,17.661179,16.685488,40.642789,75.097647,53.163171,60.145473
17,Mezzogiorno,italian,2020,21.780618,9.218436,16.074188,14.901700,38.809179,74.371937,51.099076,57.092398
18,Mezzogiorno,italian,2021,21.733578,8.411085,16.175574,15.629899,39.703686,75.412764,52.383436,58.786052
19,Mezzogiorno,italian,2022,19.364638,6.812687,14.076778,13.592164,40.331041,75.942163,53.174318,59.487311
20,Nord,foreign,2018,14.491531,9.137413,13.131091,12.781869,68.289759,76.686424,72.931198,78.395477
21,Nord,foreign,2019,13.519575,10.391808,12.223271,11.192228,68.257518,76.713407,72.899590,78.430684
22,Nord,foreign,2020,12.179855,10.897149,12.009307,12.133324,62.080906,71.332343,67.639693,74.937094
23,Nord,foreign,2021,12.367512,11.026852,12.264354,12.495783,64.769660,74.721646,70.159186,76.261093
24,Nord,foreign,2022,10.421102,8.387245,9.768999,9.457004,65.698128,76.511609,71.207475,76.864817
25,Nord,italian,2018,7.663050,3.335926,5.599697,5.546833,55.320980,86.141796,70.329751,75.863703
26,Nord,italian,2019,7.548570,3.097107,5.170383,4.881866,55.708748,85.910280,70.676994,76.024817
27,Nord,italian,2020,6.954854,3.224007,5.135753,5.120106,53.970334,84.271635,68.906944,73.921695
28,Nord,italian,2021,7.227654,2.975011,5.087200,4.995005,54.163318,85.553606,69.213628,74.061972
29,Nord,italian,2022,6.388568,2.391241,4.355185,4.254452,54.849589,86.307408,70.253738,75.355582
30,Nord-est,foreign,2018,15.381984,9.819867,13.479952,12.619294,67.473834,76.487557,73.376928,79.708734
31,Nord-est,foreign,2019,14.406747,10.068177,12.455572,11.210479,67.704574,76.943319,73.719380,79.938751
32,Nord-est,foreign,2020,12.020518,11.987181,11.897270,11.754628,62.688161,75.437066,70.304117,77.875076
33,Nord-est,foreign,2021,11.021124,9.334388,10.495161,10.315790,63.913195,77.036717,71.090152,77.882568
34,Nord-est,foreign,2022,10.030182,6.208408,8.828886,8.471354,65.197743,78.276261,71.938108,77.516503
35,Nord-est,italian,2018,6.678413,3.139968,4.941271,4.849491,55.556846,85.724218,70.800658,76.656790
36,Nord-est,italian,2019,6.202183,3.248361,4.454879,4.127024,55.295821,85.436213,71.252621,77.447567
37,Nord-est,italian,2020,6.316249,3.260684,4.876395,4.927196,54.445613,83.740433,69.573899,74.922599
38,Nord-est,italian,2021,6.397210,2.777307,4.529554,4.436290,54.174218,85.298496,69.505691,74.410024
39,Nord-est,italian,2022,5.598281,2.209158,3.837501,3.730644,55.003484,86.232490,70.747591,76.074892
40,Nord-ovest,foreign,2018,13.942550,8.657254,12.883018,12.920238,68.802661,76.827490,72.617672,77.313317
41,Nord-ovest,foreign,2019,12.974600,10.642936,12.051909,11.175751,68.601709,76.536952,72.306542,77.109207
42,Nord-ovest,foreign,2020,12.277353,9.928720,12.096275,12.508222,61.716206,68.043631,65.711014,72.239657
43,Nord-ovest,foreign,2021,13.224713,12.471011,13.596371,14.408137,65.327416,72.853186,69.474620,74.893586
44,Nord-ovest,foreign,2022,10.672936,10.163093,10.498555,10.377461,66.026004,75.131896,70.651191,76.266436
45,Nord-ovest,italian,2018,8.359876,3.474170,6.087053,6.088359,55.156700,86.439320,69.985466,75.260497
46,Nord-ovest,italian,2019,8.479393,2.987756,5.700288,5.468788,55.998608,86.256693,70.256830,74.955011
47,Nord-ovest,italian,2020,7.408154,3.197198,5.328483,5.268204,53.640038,84.664571,68.419710,73.171798
48,Nord-ovest,italian,2021,7.805801,3.120391,5.497647,5.419123,54.156985,85.742349,69.000339,73.800469
49,Nord-ovest,italian,2022,6.945924,2.522901,4.736643,4.653365,54.741921,86.361940,69.894383,74.817090

In [76]:
#creating a pivot table to have the information of the educational leval in other columns and not rows
final_mashup = DF5.pivot_table(index=['Year', 'Territory'], columns='Citizenship').reset_index()

In [77]:
final_mashup

             Year    Territory   ACT_ED_1              ACT_ED_2             \
Citizenship                       foreign    italian    foreign    italian
0            2018   Centro (I)  70.985618  52.889158  75.708602  71.418533
1            2018  Mezzogiorno  66.097724  41.577883  67.187872  59.857702
2            2018         Nord  68.289759  55.320980  78.395477  75.863703
3            2018     Nord-est  67.473834  55.556846  79.708734  76.656790
4            2018   Nord-ovest  68.802661  55.156700  77.313317  75.260497
5            2019   Centro (I)  70.615605  52.150330  76.776958  71.001206
6            2019  Mezzogiorno  66.055395  40.642789  63.178155  60.145473
7            2019         Nord  68.257518  55.708748  78.430684  76.024817
8            2019     Nord-est  67.704574  55.295821  79.938751  77.447567
9            2019   Nord-ovest  68.601709  55.998608  77.109207  74.955011
10           2020   Centro (I)  66.399470  49.991570  70.110227  69.852723
11           2020  Mezzogiorno  61.716367  38.809179  57.003637  57.092398
12           2020         Nord  62.080906  53.970334  74.937094  73.921695
13           2020     Nord-est  62.688161  54.445613  77.875076  74.922599
14           2020   Nord-ovest  61.716206  53.640038  72.239657  73.171798
15           2021   Centro (I)  66.442788  50.522212  73.098578  70.399843
16           2021  Mezzogiorno  63.320470  39.703686  59.350414  58.786052
17           2021         Nord  64.769660  54.163318  76.261093  74.061972
18           2021     Nord-est  63.913195  54.174218  77.882568  74.410024
19           2021   Nord-ovest  65.327416  54.156985  74.893586  73.800469
20           2022   Centro (I)  68.150298  51.609045  72.925446  71.828835
21           2022  Mezzogiorno  63.442347  40.331041  61.264202  59.487311
22           2022         Nord  65.698128  54.849589  76.864817  75.355582
23           2022     Nord-est  65.197743  55.003484  77.516503  76.074892
24           2022   Nord-ovest  66.026004  54.741921  76.266436  74.817090

              ACT_ED_3            UNEMP_ED_1            UNEMP_ED_2             \
Citizenship    foreign    italian    foreign    italian    foreign    italian
0            77.124190  83.546888  15.155627  11.356605  14.836710   9.377720
1            71.544665  74.639067  15.570274  24.215728  16.964263  17.254204
2            76.686424  86.141796  14.491531   7.663050  12.781869   5.546833
3            76.487557  85.724218  15.381984   6.678413  12.619294   4.849491
4            76.827490  86.439320  13.942550   8.359876  12.920238   6.088359
5            75.937080  83.869037  13.568437   9.827092  17.514611   8.193194
6            65.841146  75.097647  16.924579  23.170330  19.247073  16.685488
7            76.713407  85.910280  13.519575   7.548570  11.192228   4.881866
8            76.943319  85.436213  14.406747   6.202183  11.210479   4.127024
9            76.536952  86.256693  12.974600   8.479393  11.175751   5.468788
10           68.671068  82.418189  13.153746  10.372889  13.542032   7.821124
11           55.005406  74.371937  19.020709  21.780618  18.689590  14.901700
12           71.332343  84.271635  12.179855   6.954854  12.133324   5.120106
13           75.437066  83.740433  12.020518   6.316249  11.754628   4.927196
14           68.043631  84.664571  12.277353   7.408154  12.508222   5.268204
15           71.376057  83.899395  13.241853  11.100709  16.586291   8.114135
16           58.843586  75.412764  20.928654  21.733578  20.727722  15.629899
17           74.721646  85.553606  12.367512   7.227654  12.495783   4.995005
18           77.036717  85.298496  11.021124   6.397210  10.315790   4.436290
19           72.853186  85.742349  13.224713   7.805801  14.408137   5.419123
20           74.444015  83.923159  12.723967   8.462975  13.377200   6.500167
21           60.235821  75.942163  19.000206  19.364638  19.229423  13.592164
22           76.511609  86.307408  10.421102   6.388568   9.457004   4.254452
23           78.276261  86.232490  10.030182   5.598281   8.471354   3.730644
24           75.131896  86.361940  10.672936   6.945924  10.377461   4.653365

            UNEMP_ED_3               total_x               total_y
Citizenship    foreign    italian    foreign    italian    foreign    italian
0            10.804081   4.986898  14.453227   8.676383  73.572533  67.794273
1            17.189990  11.038761  16.046920  18.566454  66.715357  53.233826
2             9.137413   3.335926  13.131091   5.599697  72.931198  70.329751
3             9.819867   3.139968  13.479952   4.941271  73.376928  70.800658
4             8.657254   3.474170  12.883018   6.087053  72.617672  69.985466
5            11.434287   5.102061  14.846058   7.718597  73.539525  67.642946
6            16.836758  10.296681  17.526526  17.661179  65.247186  53.163171
7            10.391808   3.097107  12.223271   5.170383  72.899590  70.676994
8            10.068177   3.248361  12.455572   4.454879  73.719380  71.252621
9            10.642936   2.987756  12.051909   5.700288  72.306542  70.256830
10            8.624535   5.024784  12.778525   7.629936  68.004095  66.140077
11           17.950487   9.218436  18.871393  16.074188  59.997375  51.099076
12           10.897149   3.224007  12.009307   5.135753  67.639693  68.906944
13           11.987181   3.260684  11.897270   4.876395  70.304117  69.573899
14            9.928720   3.197198  12.096275   5.328483  65.711014  68.419710
15           18.102600   4.150024  15.194500   7.694963  69.614376  66.848048
16           19.874336   8.411085  20.808093  16.175574  61.888849  52.383436
17           11.026852   2.975011  12.264354   5.087200  70.159186  69.213628
18            9.334388   2.777307  10.495161   4.529554  71.090152  69.505691
19           12.471011   3.120391  13.596371   5.497647  69.474620  69.000339
20           12.505329   3.369947  12.980380   6.059123  70.789589  67.995490
21           17.563798   6.812687  18.971048  14.076778  62.571852  53.174318
22            8.387245   2.391241   9.768999   4.355185  71.207475  70.253738
23            6.208408   2.209158   8.828886   3.837501  71.938108  70.747591
24           10.163093   2.522901  10.498555   4.736643  70.651191  69.894383

In [78]:
final_mashup.describe()

              ACT_ED_1              ACT_ED_2              ACT_ED_3             \
Citizenship    foreign    italian    foreign    italian    foreign    italian
count        25.000000  25.000000  25.000000  25.000000  25.000000  25.000000
mean         65.990942  51.216404  73.289484  71.064583  72.342502  83.088068
std           2.621997   5.832111   6.574747   6.431047   6.319033   4.223537
min          61.716206  38.809179  57.003637  57.092398  55.005406  74.371937
25%          63.913195  50.522212  72.239657  70.399843  71.332343  83.546888
50%          66.055395  54.156985  76.261093  73.921695  75.131896  84.664571
75%          68.150298  55.003484  77.516503  75.260497  76.686424  85.910280
max          70.985618  55.998608  79.938751  77.447567  78.276261  86.439320

            UNEMP_ED_1            UNEMP_ED_2            UNEMP_ED_3             \
Citizenship    foreign    italian    foreign    italian    foreign    italian
count        25.000000  25.000000  25.000000  25.000000  25.000000  25.000000
mean         13.928813  10.694374  13.781459   7.673462  12.000308   4.534902
std           2.731966   6.027526   3.350027   4.318262   3.682003   2.559704
min          10.030182   5.598281   8.471354   3.730644   6.208408   2.209158
25%          12.277353   6.945924  11.210479   4.881866   9.819867   3.097107
50%          13.241853   7.805801  12.781869   5.468788  10.804081   3.260684
75%          15.155627  11.100709  16.586291   8.193194  12.505329   5.024784
max          20.928654  24.215728  20.727722  17.254204  19.874336  11.038761

               total_x               total_y
Citizenship    foreign    italian    foreign    italian
count        25.000000  25.000000  25.000000  25.000000
mean         13.606266   7.826844  69.518704  65.931716
std           2.946764   4.634655   3.895783   6.922151
min           8.828886   3.837501  59.997375  51.099076
25%          12.051909   4.941271  67.639693  66.848048
50%          12.883018   5.599697  70.651191  69.000339
75%          14.846058   7.718597  72.617672  70.253738
max          20.808093  18.566454  73.719380  71.252621

In [79]:
#result = DF5.loc[DF5['Citizenship'] == 'foreign']
#result.to_csv("../_datasets/F_MASHUP.csv")

In [80]:
#defining a list with the name of the most relevant columns
#infocols = ["LOCATION", "MEASURE", "TIME", "Value"]
#df3 = (pd.read_csv("../_datasets/OECD_Avarage_Wage.csv", sep=","))[infocols]
#df3

In [81]:
#selecting only information about Italy and deleting decimal numbers from value
#df3 = df3[df3["LOCATION"]=="ITA"]
#df3['Value'] = df3['Value'].astype(str)
#df3['Value'] = df3['Value'].str.replace(r'\..*$', '', regex=True)
#df3['Value'] = df3['Value'].astype(int)
#df3

In [ ]:
df4 = (pd.read_csv("../_datasets/ISTAT_Unemployment_rate_region_2018_2022_.csv", sep=","))[infocol]
df4 = df4[df4["Citizenship"]=="total"]
df4 = df4[df4["Gender"]=="total"]
df4 = df4[df4["Highest level of education attained"]=="total"]
df4 = df4[df4["Territory"]=="Italy"]
df4 = y_val(df4)
tot_unemp = df4.head(5)

In [ ]:
# Specify the path to the JSON file
file_path = "../_datasets/Clean/D4/net_income_by_regions_data.json"

# Load the JSON file
with open(file_path, "r") as file:
    data = json.load(file)

dfs = pd.DataFrame.from_dict(data['IT']) 
dfs = dfs.rename(columns={'TIME_PERIOD':'TIME'})
dfs['TIME'] = dfs['TIME'].astype(int)
dfs['ObsValue'] = dfs['ObsValue'].astype(np.float64)
dfs.info()

In [ ]:
DF6 = pd.merge(dfoecd, dfs, on=['TIME'], how='outer')
DF6

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Create a scatterplot using Seaborn
plt.figure(figsize=(10, 6))
plt.scatter(x=DF6['ObsValue'], y=DF6['Value'], label='Data Points', color='blue', marker='o')

# Add labels and a title
plt.xlabel('Annual Avarage Salary (€)')
plt.ylabel('Unemployment Rate (%)')
plt.title('Unemployment Rate x Annual Avarage Salary')

# Show the plot
plt.legend()
plt.show()

In [ ]:
# importing package 
#import matplotlib.pyplot as plt 
#import numpy as np 

# plot lines 
#plt.plot(DF6['ObsValue'], label = "line 1") 
#plt.plot(DF6['Value'], label = "line 2") 
#plt.plot(DF6['TIME'], np.sin(DF6['TIME']), label = "curve 1") 
#plt.legend() 
#plt.show()

In [ ]:
import plotly as plt
import plotly.express as px
import json
from urllib.request import urlopen
import pandas as pd

In [ ]:
with urlopen('https://raw.githubusercontent.com/openaccesstoimmigrants/openaccesstoimmigrants/main/_datasets/nuts_rg_60m_2013_lvl_1.geojson') as response:
 it_map = json.load(response)

it_map

In [ ]:
def find_key_in_json(json_data, target_key):
    found_items = []

    # Recursive function to search for the key
    def find_key_recursive(obj, key):
        if isinstance(obj, dict):
            for k, v in obj.items():
                if k == key:
                    found_items.append({k: v})
                elif isinstance(v, (dict, list)):
                    find_key_recursive(v, key)
        elif isinstance(obj, list):
            for item in obj:
                find_key_recursive(item, key)

    find_key_recursive(json_data, target_key)
    return found_items

In [ ]:
target_key = "NUTS_ID"
result = find_key_in_json(it_map, target_key)
print(result)

In [ ]:
import json

def filter_geojson_by_prefix(geojson_file, prefix):

    # Filter features based on the prefix
    filtered_features = [feature for feature in geojson_file['features'] if feature['properties']['NUTS_ID'].startswith(prefix)]

    # Create a new GeoJSON object with filtered features
    filtered_geojson = {
        "type": "FeatureCollection",
        "features": filtered_features
    }

    return filtered_geojson

# Example usage
filtered_geojson = filter_geojson_by_prefix(it_map, 'IT')
filtered_geojson

In [ ]:
target_key = "NUTS_ID"
result = find_key_in_json(filtered_geojson, target_key)
print(result)

In [ ]:
import json

def replace_value_in_geojson(geojson_file, key_to_replace, old_value, new_value):

    # Iterate through features and replace the value if found
    for feature in geojson_file['features']:
        if key_to_replace in feature['properties'] and feature['properties'][key_to_replace] == old_value:
            feature['properties'][key_to_replace] = new_value

# Applying function to replace values to be according to ISTAT division
replace_value_in_geojson(filtered_geojson, 'NUTS_ID', 'ITI', 'ITE')
replace_value_in_geojson(filtered_geojson, 'NUTS_ID', 'ITH', 'ITD')

In [ ]:
target_key = "NUTS_ID"
result = find_key_in_json(filtered_geojson, target_key)
print(result)

In [ ]:
state_id_map = {}
for feature in it_map ['features']:
 feature['id'] = feature['properties']['NUTS_ID']
 state_id_map[feature['properties']['NUTS_ID']] = feature['id']

In [ ]:
df_dist = pd.read_json('https://raw.githubusercontent.com/openaccesstoimmigrants/openaccesstoimmigrants/main/_datasets/Clean/D1(b)/combined_immigrants_distribution.json')

df_dist = df_dist[df_dist["Territory"] !="IT"]

df_dist

In [ ]:
fig = px.choropleth(
 df_dist,#soybean database
 geojson = filtered_geojson,
 locations="Territory", #define the limits on the map/geography
  #shape information
 color = "Quantity", #defining the color of the scale through the database
 hover_name = "Territory",
 hover_data =["Quantity"],
 title = "Immigrants by Region", #title of the map
 animation_frame = 'Year' #creating the application based on the year
)
fig.update_geos(fitbounds = "locations", visible = False)
fig.show()

In [ ]:
!pip install dash

In [ ]:
from dash import Dash, dcc, html, Input, Output
import plotly.express as px

app = Dash(__name__)


app.layout = html.Div([
    html.H4('Immigrants distribution'),
    html.P("Select a year:"),
    dcc.RadioItems(
        id='Year', 
        options=["2018", "2019", "2020", "2021","2022"],
        value="Quantity",
        inline=True
    ),
    dcc.Graph(id="graph"),
])


@app.callback(
    Output("graph", "figure"), 
    Input("Year", "Quantity"))
def display_choropleth(year):
    df = df_dist # replace with your own data source
    geojson = filtered_geojson
    fig = px.choropleth(
        df, geojson=geojson, color=year,
        locations="Territory", featureidkey="properties.NUTS_ID",
        projection="mercator", range_color=[0, 6500])
    fig.update_geos(fitbounds="locations", visible=False)
    fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
    return fig


app.run_server(debug=True)

## USE ISTAT DIVISION OF REGIONS FOR MAP

In [ ]:
import plotly.express as px

df = df_dist
geojson = it_map

fig = px.choropleth(df, geojson=filtered_geojson, color="Quantity",
                    locations="Territory", featureidkey="properties.NUTS_ID",
                    projection="mercator"
                   )
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()